### PR TITLE
Release 0.9.1

### PR DESCRIPTION
**Pull request by theunkn0wn1**
Bug fixes
------------------------
(regression) #107 Pydle will once again connect to password protected servers.
#111 Resolve deadlock issues relating to `.whois` and other blocking IRC methods

Docs
-------------

This release also Features a documentation build, provided ReadTheDocs's build hook on our `master` branch is still working.

### CODE REVIEW

**Comment by theunkn0wn1** [comment]
woops i most certainly meant `0.9.1`

also.. while i have you, could you add me as a maintainer on ReadTheDocs? It would make debugging RTD builds easier

**Comment by Shizmob** [comment]
Let’s talk about maintainer stuff when I get back from travels on the 17th/18th. :P
In the meantime, I re-pushed the asyncio branch you deleted because I’m fairly sure people were relying on https://github.com/Shizmob/pydle@asyncio <https://github.com/Shizmob/pydle@asyncio> in their requirements.txt and I don’t want to break those use-cases.

**Comment by LizzyTrickster** [comment]
I manually applied this change to my installed version of the Pydle library and I can confirm the change works.

**Comment by Harmon758** [comment]
@LizzyTrickster I assume you're referring to #108.
It's already been merged into the develop branch, so you can just install from that branch for the fix.

**Comment by LizzyTrickster** [comment]
Oh, i didn't see that. Thanks

**Pull request merged**
